name: tabProject
channels:
  - defaults
dependencies:
  - ca-certificates=2020.10.14
  - certifi=2020.6.20
  - openssl=1.1.1h
  - pip=20.2.4
  - portaudio=19.6.0
  - pyaudio=0.2.11
  - python=3.8.5
  - setuptools=50.3.0
  - sqlite=3.33.0
  - wheel=0.35.1
  - zlib=1.2.11
  - pip:
    - absl-py==0.11.0
    - appdirs==1.4.4
    - astunparse==1.6.3
    - audioread==2.1.9
    - cached-property==1.5.2
    - cachetools==4.1.1
    - cffi==1.14.3
    - chardet==3.0.4
    - cycler==0.10.0
    - decorator==4.4.2
    - gast==0.3.3
    - google-auth==1.23.0
    - google-auth-oauthlib==0.4.2
    - google-pasta==0.2.0
    - grpcio==1.33.2
    - h5py==2.10.0
    - idna==2.10
    - joblib==0.17.0
    - keras==2.4.3
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.1
    - librosa==0.7.2
    - llvmlite==0.32.1
    - markdown==3.3.3
    - matplotlib==3.3.2
    - numba==0.49.1
    - numpy==1.18.4
    - oauthlib==3.1.0
    - opt-einsum==3.3.0
    - packaging==20.4
    - pillow==8.0.1
    - pooch==1.2.0
    - protobuf==3.13.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pyparsing==2.4.7
    - pyqt5==5.15.1
    - pyqt5-sip==12.8.1
    - pyqtgraph==0.11.0
    - python-dateutil==2.8.1
    - pyyaml==5.3.1
    - requests==2.24.0
    - requests-oauthlib==1.3.0
    - resampy==0.2.2
    - rsa==4.6
    - scikit-learn==0.23.2
    - scipy==1.5.4
    - six==1.15.0
    - soundfile==0.10.3.post1
    - svgwrite==1.4
    - tensorboard==2.3.0
    - tensorboard-plugin-wit==1.7.0
    - tensorflow==2.3.1
    - tensorflow-estimator==2.3.0
    - termcolor==1.1.0
    - threadpoolctl==2.1.0
    - urllib3==1.25.11
    - werkzeug==1.0.1
    - wrapt==1.12.1

